import { WorkItemTable } from "../../work-items/components/WorkItemTable";
import { WorkItemCollectionEmpty,WorkItemCollectionFailure,WorkItemCollectionStale } from "../../work-items/components/WorkItemCollection";
import type { MyWorkResult } from "../model";
type Props={data:MyWorkResult;selectedWorkItemId?:string|undefined;checkedWorkItemIds:ReadonlySet<string>;hasActiveFilter:boolean;onContextSelect:(id:string)=>void;onCheckedChange:(id:string,checked:boolean)=>void;onOpen:(id:string)=>void;onReset:()=>void};
export function MyWorkCollection(props:Props){if(props.data.totalCount===0)return <MyWorkEmptyState filtered={props.hasActiveFilter} onReset={props.onReset}/>;return <>{props.data.stale&&<WorkItemCollectionStale>Showing cached My Work. This view may be out of date.</WorkItemCollectionStale>}<div className="my-work-groups">{props.data.groups.map(group=><MyWorkGroup key={group.id} group={group} {...props}/>)}</div></>}
function MyWorkGroup({group,selectedWorkItemId,checkedWorkItemIds,onContextSelect,onCheckedChange,onOpen}:Props&{group:MyWorkResult["groups"][number]}){return <section className="my-work-group" aria-labelledby={`group-${group.id}`}><header><h2 id={`group-${group.id}`}>{group.label}</h2><span>{group.items.length}</span></header><div className="my-work-table"><WorkItemTable ariaLabel={`My Work · ${group.label}`} items={group.items} selectedWorkItemId={selectedWorkItemId} checkedWorkItemIds={checkedWorkItemIds} onContextSelect={onContextSelect} onCheckedChange={onCheckedChange} onOpen={onOpen}/></div></section>}
export function MyWorkEmptyState({filtered,onReset}:{filtered:boolean;onReset:()=>void}){return <WorkItemCollectionEmpty title={filtered?"No matching Work Items":"No assigned Work Items yet"} description={filtered?"Adjust or clear the current search and filters.":"Work assigned to you in the Product workspace will appear here."} action={filtered?<button type="button" className="reset-view" onClick={onReset}>Reset view</button>:undefined}/>}
export function MyWorkFailure(){return <WorkItemCollectionFailure>Could not load My Work. Your current view is preserved.</WorkItemCollectionFailure>}
export function MyWorkLoading(){return <div className="my-work-skeleton" aria-label="Loading My Work"><div className="group-skeleton"/>{Array.from({length:7},(_,i)=><div key={i} className="skeleton-row"><span/><span/><span/><span/></div>)}</div>}
